name: Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tpoechtrager/osxcross

      - name: Prepare build
        run: |
          curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz -o tarballs/MacOSX11.3.sdk.tar.xz

      - name: Build
        env:
          UNATTENDED: 1
        run: ./build.sh

      - name: Prepare publish
        if: github.event_name == 'release'
        run: |
          mv target crossosx
          tar -zcvf crossosx.tar.gz crossosx
          tar --zstd -cvf crossosx.tar.zst crossosx

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: |
            crossosx.tar.gz
            crossosx.tar.zst
